// English texts for the game data (applied over the French data when the game runs in English).

export default {
  seasons: ['Spring', 'Summer', 'Autumn', 'Winter'],
  terrain: [
    { name: 'Meadow' }, { name: 'Forest' }, { name: 'Rocks' }, { name: 'Water' }, { name: 'Mountain' },
    { name: 'Fertile soil', hint: 'Farms and vineyards produce +50% here.' },
    { name: 'Sand' },
    { name: 'Tropical soil', hint: 'The only place where spices grow.' },
    { name: 'Gold vein', hint: 'A gold mine must touch it.' },
  ],
  goods: {
    wood: 'Wood', planks: 'Planks', stone: 'Stone', fish: 'Fish', wheat: 'Wheat', flour: 'Flour', bread: 'Bread',
    wool: 'Wool', cloth: 'Cloth', beer: 'Beer', ore: 'Iron ore', coal: 'Charcoal', iron: 'Iron', tools: 'Tools',
    grapes: 'Grapes', wine: 'Wine', spices: 'Spices', nugget: 'Gold nuggets', jewels: 'Jewellery',
  },
  gold: 'Gold',
  classes: [
    { name: 'Peasants', one: 'peasant', house: 'Cottage' },
    { name: 'Artisans', one: 'artisan', house: 'House' },
    { name: 'Burghers', one: 'burgher', house: 'Townhouse' },
    { name: 'Nobles', one: 'noble', house: 'Mansion' },
  ],
  needs: {
    'Nourriture (poisson ou pain)': 'Food (fish or bread)',
    'Eau (puits)': 'Water (well)',
    'Marché': 'Market',
    'Chapelle': 'Chapel',
    'Taverne': 'Tavern',
    'École': 'School',
    'Médecin': 'Doctor',
    'Sécurité (poste de garde)': 'Safety (guard post)',
    'Beauté du quartier ≥ 2': 'Neighbourhood beauty ≥ 2',
    'Beauté du quartier ≥ 4': 'Neighbourhood beauty ≥ 4',
  },
  taxes: ['Low', 'Normal', 'High'],
  eras: ['Hamlet', 'Village', 'Market town', 'Town', 'City', 'Capital'],
  categories: { tools: 'Tools', house: 'Housing', raw: 'Resources', industry: 'Workshops', service: 'Services', deco: 'Beauty' },
  tools: {
    inspect: { name: 'Inspect', desc: 'Tap a building to see its details.' },
    road: { name: 'Road', desc: 'Drag to lay a road. Every building must be connected to the town hall.' },
    clear: { name: 'Clear', desc: 'Drag over an area to remove forests (5 gold) and rocks (15 gold).' },
    demolish: { name: 'Demolish', desc: 'Drag over an area to destroy roads and buildings (50% refunded).' },
    fill: { name: 'Reclaim land', desc: 'Drag along the coast to reclaim land from the sea. Two islands can never be joined.' },
  },
  buildings: {
    townhall: { name: 'Town hall', desc: 'The heart of the city: roads start here. Also acts as a small market.' },
    house: { name: 'Dwelling', desc: 'Houses peasants. Upgrades by itself when its residents are satisfied and the era allows it.' },
    lumber: { name: 'Woodcutter', desc: 'Must touch a forest.' },
    fisher: { name: 'Fisherman', desc: 'Must touch water. Smaller catch in winter.' },
    quarry: { name: 'Quarry', desc: 'Must touch rocks.' },
    farm: { name: 'Wheat farm', desc: '+50% on fertile soil. Almost nothing in winter, big harvest in autumn.' },
    sheep: { name: 'Sheep farm', desc: 'Raises sheep for their wool.' },
    charcoal: { name: 'Charcoal burner', desc: 'Turns wood into charcoal. High fire risk.' },
    mine: { name: 'Iron mine', desc: 'Must touch a mountain.' },
    vineyard: { name: 'Vineyard', desc: '+50% on fertile soil. Grape harvest in autumn.' },
    spicefarm: { name: 'Spice plantation', desc: 'Only on tropical soil (spice island).' },
    goldmine: { name: 'Gold mine', desc: 'Must touch a gold vein (gold island).' },
    sawmill: { name: 'Sawmill', desc: 'Cuts wood into planks.' },
    warehouse: { name: 'Warehouse', desc: '+100 storage for every good.' },
    mill: { name: 'Mill', desc: 'Grinds wheat into flour.' },
    bakery: { name: 'Bakery', desc: 'Bakes flour into bread. High fire risk.' },
    weaver: { name: 'Weaver', desc: 'Weaves wool into cloth.' },
    brewery: { name: 'Brewery', desc: 'Brews wheat into beer.' },
    smelter: { name: 'Smelter', desc: 'Smelts ore and charcoal into iron. High fire risk.' },
    forge: { name: 'Forge', desc: 'Forges iron into tools.' },
    winepress: { name: 'Wine press', desc: 'Presses grapes into wine.' },
    jeweler: { name: 'Goldsmith', desc: 'Crafts gold nuggets into jewellery.' },
    mint: { name: 'Mint', desc: 'Strikes 10 gold a day from 1 iron.' },
    well: { name: 'Well', desc: 'Supplies water to houses within 4 tiles and helps fight fires.' },
    firestation: { name: 'Fire station', desc: 'Prevents fires within 6 tiles and quickly puts them out.' },
    market: { name: 'Market square', desc: 'Supplies houses within 7 tiles.' },
    chapel: { name: 'Chapel', desc: 'Worship for houses within 7 tiles.' },
    tavern: { name: 'Tavern', desc: 'Entertains houses within 6 tiles.' },
    school: { name: 'School', desc: 'Educates houses within 7 tiles.' },
    tower: { name: 'Watchtower', desc: 'Protects against bandits if it covers the town hall (9 tiles).' },
    port: { name: 'Harbour', desc: 'Links the islands by ship. A harbour on the main island plus a harbour on another island make a colony: its roads start from its harbour.' },
    trading: { name: 'Trading post', desc: 'Better trade prices and more frequent caravans.' },
    wonder: { name: 'Great Cathedral', desc: 'The wonder of your city: a 120-day building site that uses 4 stone, 2 planks and 1 tool every day (work stops if they run out). Completing it wins the game.' },
    royalgarden: { name: 'Royal Gardens', desc: 'Great monument: a 60-day building site (2 stone and 1 plank a day). Beauty +6 over 9 tiles and satisfaction of the whole city +3%.' },
    arena: { name: 'Arena', desc: 'Great monument: a 90-day building site (4 stone and 1 tool a day). Entertains houses within 16 tiles and satisfaction of the whole city +5%.' },
    lighthouse: { name: 'Great Lighthouse', desc: 'Great monument by the water: a 75-day building site (3 stone and 1 plank a day). Merchants flock in: purchases 20% cheaper, sales 20% dearer.' },
    palace: { name: 'Royal Palace', desc: 'The greatest monument: a 150-day building site (5 stone, 2 tools and 1 cloth a day). Taxes of the whole city +25% and beauty +5 over 8 tiles.' },
    library: { name: 'Library', desc: 'Scholars study here: +1 research point per day.' },
    university: { name: 'University', desc: '+4 research points per day.' },
    doctor: { name: 'Doctor', desc: 'Cares for houses within 7 tiles and protects them from epidemics.' },
    hospital: { name: 'Hospital', desc: 'Cares for houses within 12 tiles.' },
    guardpost: { name: 'Guard post', desc: 'Keeps houses within 7 tiles safe and limits burglaries.' },
    garden: { name: 'Garden', desc: 'Beauty +1 for houses within 3 tiles.' },
    fountain: { name: 'Fountain', desc: 'Beauty +2 (4 tiles) and supplies water like a well.' },
    statue: { name: 'Statue', desc: 'Beauty +3 for houses within 5 tiles.' },
    park: { name: 'Park', desc: 'Beauty +3 for houses within 5 tiles.' },
    ruins: { name: 'Ruins', desc: 'The remains of a burnt building. Demolish them to free the space.' },
  },
  techs: {
    axes: ['Sharpened axes', 'Woodcutters +25%.'],
    nets: ['Large nets', 'Fishermen +25%.'],
    masonry: ['Masonry', 'House fire risk −40%.'],
    accounting: ['Accounting', 'Storage +50 per good.'],
    plough: ['Heavy plough', 'Wheat farms +25%.'],
    watermill: ['Milling', 'Mills and bakeries +20%.'],
    loom: ['Weaving loom', 'Sheep farms and weavers +25%.'],
    medicine: ['Medicine', 'Unlocks the doctor.'],
    militia: ['Militia', 'Unlocks the guard post.'],
    firepump: ['Fire pump', 'Fire station range +2.'],
    administration: ['Administration', 'Building upkeep −15%.'],
    hops: ['Hops', 'Breweries +30%.'],
    blast: ['Blast furnace', 'Charcoal burners, smelters and forges +25%.'],
    cadastre: ['Land registry', 'Taxes +10%.'],
    hygiene: ['Hygiene', 'Satisfaction of all residents +5%.'],
    navigation: ['Navigation', 'Unlocks the harbour and colonising nearby islands.'],
    printing: ['Printing press', 'Research +30% and school range +2.'],
    surgery: ['Surgery', 'Unlocks the hospital.'],
    vines: ['Vine pruning', 'Vineyards and wine presses +25%.'],
    colonial: ['Colonial trade', 'Unlocks spice plantations and gold mines on the islands.'],
    goldsmith: ['Goldsmithing', 'Unlocks the goldsmith (jewellery).'],
    banking: ['Banking', 'Taxes +15%.'],
    architecture: ['Architecture', 'Great Cathedral building site −35%.'],
    astronomy: ['Astronomy', 'Satisfaction +5% and research +30%.'],
  },
  quests: [
    'Build 4 dwellings along the roads',
    'Build a fisherman by the water',
    'Build a woodcutter by a forest',
    'Build a well near the houses',
    'Build a sawmill',
    'Reach 30 peasants',
    'Build a fire station',
    'Reach 60 peasants',
    'Advance to the Village era',
    'Make bread: farm, mill and bakery',
    'Make cloth: sheep farm and weaver',
    'Build a chapel and a market',
    'Reach 40 artisans',
    'Advance to the Market town era',
    'Make tools: mine, charcoal burner, smelter, forge',
    'Build a brewery, a tavern and a school',
    'Reach 40 burghers',
    'Advance to the Town era',
    'Make wine: vineyard and wine press',
    'Build a harbour on the main island',
    'Found a colony: a harbour on another island',
    'Harvest spices and gold nuggets',
    'Make jewellery at a goldsmith',
    'Reach 40 nobles',
    'Advance to the City era',
    'Complete the Great Cathedral',
    'Complete the Royal Gardens',
    'Reach 2,000 residents',
    'Complete the Great Lighthouse',
    'Complete the Arena',
    'Reach 150 nobles',
    'Advance to the Capital era',
    'Complete the Royal Palace',
  ],
  renown: ['Prosperous city', 'Great city', 'Royal city', 'Jewel of the kingdom', 'Capital of the kingdom', 'Legendary metropolis'],
  difficulties: [
    ['Easy', 'More resources at start, generous taxes, few fires.'],
    ['Normal', 'The intended experience.'],
    ['Hard', 'Tight start, costly upkeep, frequent fires and setbacks.'],
  ],
  scenarios: {
    colons: { name: 'The first settlers', intro: 'A handful of settlers land on a wild island. Turn it into a proper village before the end of the third year.', goals: ['Reach 80 peasants', 'Build a sawmill', 'Advance to the Village era'] },
    hiver: { name: 'The long winter', intro: 'Autumn is ending and the stores are almost empty. Hold out until spring without letting your hamlet waste away.', goals: ['Hold out until spring (day 121)', 'Have at least 50 residents in spring'], lose: 'The hamlet has been abandoned.' },
    incendie: { name: 'The great fire', intro: 'Your town grew too fast, without a single firefighter. Fire has just broken out in several houses: save what you can, then rebuild.', goals: ['Build 4 fire stations', 'Reach 400 residents'] },
    pain: { name: 'Bread and cloth', intro: 'The artisans want fresh bread and clothes. Set up the wheat and wool chains and keep them happy.', goals: ['Reach 150 artisans', 'Average satisfaction of at least 85%'] },
    savoir: { name: 'City of knowledge', intro: 'The king wants your town to become a beacon of learning. Build libraries and a university and push science forward.', goals: ['Discover 12 technologies', 'Build a university'] },
    horizons: { name: 'New horizons', intro: 'Your navigators have spotted distant islands rich in spices and gold. Found colonies and bring back their treasures.', goals: ['Found 2 colonies', 'Have 80 spices in stock', 'Have 30 gold nuggets in stock'] },
    joyau: { name: 'Jewel of the kingdom', intro: 'The kingdom\'s nobility is looking for a city worthy of its rank. Offer them spices, wine and jewellery.', goals: ['Reach 100 nobles', 'Have 40 jewellery in stock'] },
    cathedrale: { name: 'The Great Cathedral', intro: 'The ultimate challenge, on hard difficulty: start from nothing and complete the Great Cathedral.', goals: ['Complete the Great Cathedral'] },
  },
  islands: {
    home: ['Main island', ''],
    spice: ['Spice island', 'Tropical soil for spice plantations.'],
    gold: ['Gold island', 'Gold veins for gold mines.'],
    fertile: ['Green island', 'Wide fertile lands.'],
    ore: ['Iron island', 'Mountains rich in iron ore.'],
  },
};
